name: Build Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: DesktopHLE-Windows-x64
        path: target/release/desktophle.exe